const projects = [
  { number: '01', title: 'LG CDC Portal', type: 'LG CDC Portal / Web Design', year: '2025.07~09', tone: 'ink' },
  { number: '02', title: 'LG Beta Program', type: 'LG Beta Program / webOS TV & UI Design', year: '2026.07', tone: 'soft' },
  { number: '03', title: 'AX Nexus', type: 'AX Nexus / Web Planning · UX/UI Design', year: '2025.10', tone: 'line' },
  { number: '04', title: 'LG Overlay', type: 'LG Overlay / WebOS · UX/UI Planning & Design', year: '2026.03~07', tone: 'grid' },
  { number: '05', title: 'LG LATS Icon', type: 'LG Product / Icon Design', year: '2025.2026', tone: 'soft' },
  { number: '06', title: 'IM 운행 톡', type: 'IM 뱅크 IM 운행 톡 / App Design', year: '2025', tone: 'line' },
  { number: '07', title: 'IM 뱅크 캠퍼스페이', type: 'IM 뱅크 Campus Pay / UX/UI Design', year: '2026', tone: 'ink' },
  { number: '08', title: 'FitOn', type: 'FitOn / App Design', year: '2024', tone: 'grid' },
  { number: '09', title: '동네스타', type: '동네스타 / App Design', year: '2024', tone: 'soft' },
  { number: '10', title: '하루달', type: 'Haru Dal / App Design', year: '2024', tone: 'line' },
];
export default function Home() { return <main><nav className="nav shell"><a className="wordmark" href="#top">CY<span>—</span></a><div className="nav-links"><a href="#about">About</a><a href="#works">Works</a><a href="#contact">Contact</a></div><a className="availability" href="#contact"><i /> Open to new opportunities</a></nav><section className="hero shell" id="top"><p className="eyebrow">UI/UX Designer · 3+ Years Experience</p><h1>Designing digital<br /><em>experiences</em> with intent</h1><div className="hero-bottom"><p>I’m Chaeyoung, a UI/UX designer creating clear, considered products for people and brands that care about the details.</p><a className="circle-arrow" href="#works" aria-label="View selected works">↘</a></div></section><section className="about shell" id="about"><p className="section-label">01 — About</p><div className="about-grid about-statement"><p><strong>UI/UX 디자인</strong>을 중심으로 다양한 디지털 서비스를 경험하며 <strong>사용자와 서비스의 목적</strong>을 연결하는 디자인을 만들어왔습니다.<br />화면의 구조와 흐름을 세심하게 고민하고, 기획 의도를 이해하며 <strong>더 나은 경험</strong>으로 이어질 수 있도록 디자인합니다.</p></div></section><section className="works shell" id="works"><div className="section-head"><p className="section-label">02 — Selected works</p><p className="muted">A selection of recent collaborations</p></div><div className="project-list">{projects.map((project) => <a className="project project-link" href={`/work/${project.number}`} key={project.number}><div className={`project-visual ${project.tone}`}><span>{project.number}</span><b>{project.tone === 'ink' ? 'FLOW' : project.tone === 'soft' ? 'morrow' : project.tone === 'line' ? 'AO' : 'NOMA'}</b></div><div className="project-info"><div><h3>{project.title}</h3><p>{project.type}</p></div><span>{project.year} <i>↗</i></span></div></a>)}</div></section><section className="contact shell" id="contact"><p className="section-label">03 — Contact</p><div className="contact-content"><h2>Thank You for <em>watching</em></h2><div className="contact-links"><a className="email" href="mailto:kcy8053@naver.com">kcy8053@naver.com <span>↗</span></a><a className="phone" href="tel:010-4233-8053">010-4233-8053 <span>↗</span></a></div></div><div className="contact-foot"><span>Let’s make something meaningful.</span><span>© 2026 Chaeyoung Portfolio</span></div></section></main>; }
