import Link from 'next/link';
const data: Record<string,{title:string;type:string;year:string;tag:string;copy:string;tone:string;demo?:string}> = {
  '01': { title:'LG CDC Portal', type:'LG CDC Portal / Web Design', year:'2025', tag:'LG 사내 디자인 플랫폼 디자인', copy:'LG 디자이너를 위한 사내 디자인 포털로, 디자인 레퍼런스와 히스토리, 뉴스, 커뮤니티, 공간 및 장비 예약 등 디자인 업무를 지원하는 다양한 기능을 제공합니다.\n\n서비스 전반의 UX/UI 구조와 주요 화면을 설계하고, 기획자와 요구사항 및\n사용자 흐름을 조율하며 일관된 디자인 방향을 구축했습니다.', tone:'lg-cdc', demo:'http://1.234.83.56:3540/' },
  '02': { title:'LG Beta Program', type:'LG Beta Program / webOS TV & UI Design', year:'2026', tag:'LG 베타프로그램 앱 및 관리자화면 디자인', copy:'LG Beta Program은 LG 제품 및 서비스의 신규 기능을\n사용자가 직접 테스트하고 피드백을 전달할 수 있는 베타 테스트 플랫폼입니다.\n\nTV 앱과 관리자 화면의 UX/UI 디자인을 담당하여,\n사용자와 운영자 각각의 환경에 최적화된 경험을 설계했습니다.', tone:'lg-beta' },
  '03': { title:'AX Nexus / 국책과제', type:'AX Nexus / Web Planning · UX/UI Design', year:'2025', tag:'고난이도 AX 연구를 지원하는 플랫폼 기획 및 디자인', copy:'고난이도 AX 연구 및 개발을 지원하기 위한 플랫폼으로, 연구 과제와 관련된 정보와 서비스를 체계적으로 관리하고 활용할 수 있도록 구성했습니다.\n\n플랫폼의 목적과 사용자 흐름을 바탕으로 정보 구조와 콘텐츠를 기획하고, 페이지 구성부터 UX/UI 설계 및 비주얼 디자인까지 웹사이트 구축 전반을 주도했습니다.', tone:'ax-nexus', demo:'https://axnexus.net/' },
  '04': { title:'LG Overlay 서비스', type:'LG Overlay / WebOS · UX/UI Planning & Design', year:'2026', tag:'TV 시청과 쇼핑을 연결하는\nwebOS 서비스 기획 및 디자인', copy:'TV 콘텐츠 속 음식이나 의류 등의 상품을 인식하고, 관련 상품을 바로 확인하고 쇼핑할 수 있도록 연결하는 webOS 기반 서비스입니다.\n\n서비스의 전체 구조와 사용자 플로우를 기획하고 주요 기능 및 화면을 설계했으며, Figma를 활용해 기획부터 UX/UI 디자인까지 진행했습니다.', tone:'lg-overlay' },
  '05': { title:'LG Product Icon Design', type:'LG LATS / Icon Design', year:'2025,2026', tag:'LG 내부 서비스에 사용되는 제품 및 기능 아이콘 디자인', copy:'LG 내부 서비스에서 제품 정보를 직관적으로 전달하고 기능을 쉽게 인지할 수 있도록 다양한 LG 제품 및 기능 아이콘을 제작했습니다.\n\nLG 제품의 형태와 특징을 직관적으로 표현하고, 일관된 스타일로 활용될 수 있도록 아이콘의 형태와 비율을 설계했습니다. 다양한 기능과 용도에 맞는 아이콘을 제작하여 내부 서비스의 UI에 적용했습니다.', tone:'lg-icons' },
  '06': { title:'IM 뱅크 IM운행톡', type:'IM 뱅크 IM운행톡 / App Design', year:'2026', tag:'택시 운행 수입 현황을 한눈에\n확인할 수 있는 모바일 앱 리디자인', copy:'택시 운행에 따른 수입과 운행 정보를 확인하고 관리할 수 있는 모바일 앱으로, IM뱅크의 새로운 브랜드 아이덴티티를 반영하고 주요 수입 정보를 보다 직관적으로 확인할 수 있도록 앱을 리디자인했습니다.\n\n기존 화면의 정보 구조와 사용성을 개선하고, IM뱅크의 새로운 브랜드 컬러를 적용해 시각적 일관성을 강화했습니다. 또한 수입 현황을 한눈에 파악할 수 있도록 정보의 우선순위와 레이아웃을 재구성하여 직관적인 사용자 경험을 설계했습니다.', tone:'im-bank', demo:'https://play.google.com/store/search?q=im%EC%9A%B4%ED%96%89%ED%86%A1&c=apps&hl=ko' },
  '07': { title:'IM뱅크 캠퍼스페이', type:'IM뱅크 Campus Pay / UX/UI Design', year:'2026', tag:'학교 생활과 결제를 연결하는 QR 결제 서비스', copy:'학교 급식과 매점 등에서 QR코드로 결제하고, 가맹점 및 관리자 기능까지 통합 제공하는 캠퍼스 전용 결제 서비스입니다.\n\n학생용 결제 화면부터 가맹점 관리 및 관리자 페이지까지 서비스 전반의 UX/UI를 설계하고 디자인했습니다. 각 사용자와 운영 환경에 맞춰 정보 구조와 화면을 구성하고, 일관된 UI 경험을 구축했습니다.', tone:'campus-pay' },
  '08': { title:'FitOn APP', type:'FitOn / App Design', year:'2025', tag:'운동부터 식단과 생활 습관까지 관리하는 헬스케어 앱', copy:'운동 자세와 운동 기록을 확인하고, 식단과 수분 섭취량까지 관리할 수 있는\n개인 맞춤형 운동·건강 관리 앱입니다.\n\n운동과 식단, 수분 섭취 등 다양한 건강 정보를 쉽게 기록하고 확인할 수 있도록 콘텐츠와 기능을 체계적으로 구성했습니다. 사용자가 자신의 운동 상태와 생활 습관을 직관적으로 파악하고 꾸준히 관리할 수 있도록 화면과 인터랙션을 디자인했습니다.', tone:'fiton' },
  '09': { title:'동네스타 APP', type:'동네스타 / App Design', year:'2024', tag:'등록된 결제정보를 활용한 자동 쿠폰 적립 서비스', copy:'등록된 결제정보를 기반으로 매장 방문 및 결제 시 쿠폰을 자동으로 적립하고, 적립한 쿠폰을 매장에서 편리하게 사용할 수 있는 모바일 서비스입니다.\n\n매장 탐색과 쿠폰 이용 과정의 정보 구조를 정리하고, 주요 기능을 직관적으로 전달할 수 있도록 화면을 구성했습니다.', tone:'local-star' },
  '10': { title:'하루달', type:'Haru Dal / App Design', year:'2024', tag:'일정과 루틴을 한눈에 관리하는 캘린더 앱 디자인', copy:'일정과 할 일부터 습관과 루틴까지 캘린더를 중심으로 관리할 수 있는 일정 관리 앱입니다. AI Chatting, 통계 및 검색 기능을 통해 일정을 보다 편리하게 관리할 수 있도록 구성했습니다.\n\n서비스의 전체 UX/UI를 설계하고, 주요 기능과 화면을 디자인했습니다. 캘린더를 중심으로 정보 구조와 사용자 흐름을 정리하고, 일정과 루틴을 직관적으로 확인하고 관리할 수 있도록 화면을 구성했습니다.', tone:'haru-dal' },
};
export function generateStaticParams() { return Object.keys(data).map((id) => ({ id })); }
export const dynamicParams = false;
export const dynamic = 'force-static';
export default function Work({ params }: { params: { id: string } }) { const { id } = params; const item = data[id] || data['01']; const roles = id === '01' ? <>UX/UI Design<br />Planning Collaboration<br />Development Collaboration<br />Design participation 100%</> : <>UX/UI design<br />Design system<br />Design participation 100%</>; return <main className="detail-page"><header className="detail-nav shell"><a className="wordmark" href="/">CP<span>—</span></a><a href="/#works" className="back"><svg className="svg-arrow" viewBox="0 0 16 16" aria-hidden="true"><path d="M2 8h11M9 4l4 4-4 4" /></svg> Back to works</a></header><div className="detail-grid shell"><div className="detail-left"><div className={`detail-art ${item.tone}`}>{id === '02' ? <img src="/lg-betaprogram.webp" alt="LG BetaProgram 앱 및 관리자 화면 디자인" /> : <><span>{id}</span><b>{item.tone === 'ink' ? 'FLOW' : item.tone === 'soft' ? 'morrow' : item.tone === 'line' ? 'AO' : 'NOMA'}</b></>}</div><p className="scroll-note">Scroll to explore project <span><svg className="svg-arrow" viewBox="0 0 16 16" aria-hidden="true"><path d="M2 8h11M9 4l4 4-4 4" /></svg></span></p></div><article className="detail-copy"><p className="eyebrow">{item.type} · {item.year}</p><h1>{item.title}</h1><h2>{item.tag}</h2><p className="detail-body">{item.copy}</p>{item.demo && <div className="demo-link"><p>※ LG 내부 서비스로, 포트폴리오에서는 데모 사이트로 제공됩니다 ※</p><a href={item.demo} target="_blank" rel="noreferrer">Visit demo site <span><svg className="svg-arrow" viewBox="0 0 16 16" aria-hidden="true"><path d="M2 8h11M9 4l4 4-4 4" /></svg></span></a></div>}<dl><dt>My role</dt><dd>{roles}</dd></dl><a className="next-work" href={`/work/${id === '10' ? '01' : String(Number(id)+1).padStart(2,'0')}`}>Next project <span><svg className="svg-arrow" viewBox="0 0 16 16" aria-hidden="true"><path d="M2 8h11M9 4l4 4-4 4" /></svg></span></a></article></div></main>; }
